[build]
    functions = "functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "http://localhost:3000/*"
  status = 200